#!/bin/sh

#SVR_URL="ec2-3-0-89-45.ap-southeast-1.compute.amazonaws.com"
SVR_URL="ip-172-31-2-163.ap-southeast-1.compute.internal"
TUTO="tuto/1"
TUTO_URL=${SVR_URL}/${TUTO}
ES_URL="elasticsearch-6.5.4.rpm"
ES_ETC="/etc/elasticsearch"
ES_MYML="elasticsearch.yml"
ES_ADDYML="ymladd.yml"
ES_JVM="jvm.options"
ES_NODEIP=$(ifconfig | grep inet | grep -vE '127.0.0.1|inet6' | awk '{print $2}')
ES_NODENAME=$(hostname -s)

KB_URL="kibana-6.5.4-x86_64.rpm"
KB_ETC="/etc/kibana"
KB_MYML="kibana.yml"

# ES Package Install
function install_es_packages
{
    git > /dev/null
    if [ $? -ne 1 ]; then
        sudo yum -y install git
    fi
    
    wget 2> /dev/null
    if [ $? -ne 1 ]; then
        sudo yum -y install wget
    fi
 
    java -version 2> /dev/null
    if [ $? -ne 0 ]; then
        sudo yum -y install java
    fi
    
    ls -alh /usr/local/src/elasticsearch* 2> /dev/null
    if [ $? -ne 0 ]; then
        sudo wget -q ${TUTO_URL}/${ES_URL} -O /usr/local/src/${ES_URL}
    fi
    
    rpm -ql elasticsearch > /dev/null
    if [ $? -ne 0 ]; then
        sudo rpm -ivh /usr/local/src/${ES_URL}
    fi
}

# elasticsearch.yml Configure
function configure_es_yaml
{
    sudo cp ${ES_ETC}/${ES_MYML} ${ES_ETC}/${ES_MYML}.org_1st
    sudo wget -q ${TUTO_URL}/${ES_MYML}.1st -O ${ES_ETC}/${ES_MYML}
    sudo echo "### For ClusterName & Node Name" | sudo tee -a ${ES_ETC}/${ES_MYML} > /dev/null
    sudo echo "cluster.name: mytuto-es" | sudo tee -a ${ES_ETC}/${ES_MYML} > /dev/null
    sudo echo "node.name: $ES_NODENAME" | sudo tee -a ${ES_ETC}/${ES_MYML} > /dev/null
    sudo curl -s ${TUTO_URL}/${ES_ADDYML}.1st | sudo tee -a ${ES_ETC}/${ES_MYML} > /dev/null
    
    # jvm options Configure for Heap Memory
    sudo cp ${ES_ETC}/${ES_JVM} ${ES_ETC}/${ES_JVM}.org_1st
    sudo wget -q ${TUTO_URL}/${ES_JVM}.1st -O ${ES_ETC}/${ES_JVM}
    
}

# Start Elasticsearch
function start_es_process
{
    sudo systemctl daemon-reload
    sudo systemctl enable elasticsearch.service
    sudo systemctl restart elasticsearch
}

# Kibana Package Install
function install_kb_packages
{
    java -version 2> /dev/null
    if [ $? -ne 0 ]; then
        sudo yum -y install java
    fi
    
    ls -alh /usr/local/src/kibana* 2> /dev/null
    if [ $? -ne 0 ]; then
        sudo wget -q ${TUTO_URL}/${KB_URL} -O /usr/local/src/${KB_URL}
    fi
    
    rpm -ql kibana > /dev/null
    if [ $? -ne 0 ]; then
        sudo rpm -ivh /usr/local/src/${KB_URL}
    fi
}

# kibana.yml Configure
function configure_kb_yaml
{
    sudo cp ${KB_ETC}/${KB_MYML} ${KB_ETC}/${KB_MYML}.org_1st
    sudo wget -q ${TUTO_URL}/${KB_MYML} -O ${KB_ETC}/${KB_MYML}
}

# Start Kibana
function start_kb_process
{
    sudo systemctl daemon-reload
    sudo systemctl enable kibana.service
    sudo systemctl restart kibana
}

if [ -z $1 ]; then
        echo "##################### Menu ##############"
        echo " $ ./tuto1 [Command]"
        echo "#####################%%%%%%##############"
        echo "         1 : install java & elasticsearch packages"
        echo "         2 : configure elasticsearch.yml & jvm.options"
        echo "         3 : start elasticsearch process"
        echo "         4 : install kibana packages"
        echo "         5 : configure kibana.yml"
        echo "         6 : start kibana process"
        echo "#########################################";
        exit 1;
fi

case "$1" in
        "1" ) install_es_packages;;
        "2" ) configure_es_yaml;;
        "3" ) start_es_process;;
        "4" ) install_kb_packages;;
        "5" ) configure_kb_yaml;;
        "6" ) start_kb_process;;
        *) echo "Incorrect Command" ;;
esac
